package net.fungoussoup.tintedgrove.datagen;

import net.fungoussoup.tintedgrove.TintedGrove;
import net.fungoussoup.tintedgrove.block.ModBlocks;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.tags.BlockTags;
import net.neoforged.neoforge.common.data.BlockTagsProvider;
import net.neoforged.neoforge.common.data.ExistingFileHelper;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.CompletableFuture;

public class ModBlockTagProvider extends BlockTagsProvider {
    public ModBlockTagProvider(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider, @Nullable ExistingFileHelper existingFileHelper) {
        super(output, lookupProvider, TintedGrove.MOD_ID, existingFileHelper);
    }

    @Override
    protected void addTags(HolderLookup.Provider provider) {
        tag(BlockTags.MINEABLE_WITH_AXE)
                .add(ModBlocks.RED_LOG.get())
                .add(ModBlocks.RED_WOOD.get())
                .add(ModBlocks.STRIPPED_RED_WOOD.get())
                .add(ModBlocks.STRIPPED_RED_LOG.get())
                .add(ModBlocks.RED_PLANK.get())
                .add(ModBlocks.RED_WOOD_STAIRS.get())
                .add(ModBlocks.RED_WOOD_SLAB.get())
                .add(ModBlocks.RED_WOOD_BUTTON.get())
                .add(ModBlocks.RED_WOOD_PRESSURE_PLATE.get())
                .add(ModBlocks.RED_WOOD_FENCE.get())
                .add(ModBlocks.BLUE_WOOD_FENCE_GATE.get())
                .add(ModBlocks.RED_WOOD_DOOR.get())
                .add(ModBlocks.RED_WOOD_TRAPDOOR.get())
                
                .add(ModBlocks.BLUE_LOG.get())
                .add(ModBlocks.BLUE_WOOD.get())
                .add(ModBlocks.STRIPPED_BLUE_WOOD.get())
                .add(ModBlocks.STRIPPED_BLUE_LOG.get())
                .add(ModBlocks.BLUE_PLANK.get())
                .add(ModBlocks.BLUE_WOOD_STAIRS.get())
                .add(ModBlocks.BLUE_WOOD_SLAB.get())
                .add(ModBlocks.BLUE_WOOD_BUTTON.get())
                .add(ModBlocks.BLUE_WOOD_PRESSURE_PLATE.get())
                .add(ModBlocks.BLUE_WOOD_FENCE.get())
                .add(ModBlocks.BLUE_WOOD_FENCE_GATE.get())
                .add(ModBlocks.BLUE_WOOD_DOOR.get())
                .add(ModBlocks.BLUE_WOOD_TRAPDOOR.get())
                
                .add(ModBlocks.GREEN_LOG.get())
                .add(ModBlocks.GREEN_WOOD.get())
                .add(ModBlocks.STRIPPED_GREEN_WOOD.get())
                .add(ModBlocks.STRIPPED_GREEN_LOG.get())
                .add(ModBlocks.GREEN_PLANK.get())
                .add(ModBlocks.GREEN_WOOD_STAIRS.get())
                .add(ModBlocks.GREEN_WOOD_SLAB.get())
                .add(ModBlocks.GREEN_WOOD_BUTTON.get())
                .add(ModBlocks.GREEN_WOOD_PRESSURE_PLATE.get())
                .add(ModBlocks.GREEN_WOOD_FENCE.get())
                .add(ModBlocks.GREEN_WOOD_FENCE_GATE.get())
                .add(ModBlocks.GREEN_WOOD_DOOR.get())
                .add(ModBlocks.GREEN_WOOD_TRAPDOOR.get())
                
                .add(ModBlocks.YELLOW_LOG.get())
                .add(ModBlocks.YELLOW_WOOD.get())
                .add(ModBlocks.STRIPPED_YELLOW_WOOD.get())
                .add(ModBlocks.STRIPPED_YELLOW_LOG.get())
                .add(ModBlocks.YELLOW_PLANK.get())
                .add(ModBlocks.YELLOW_WOOD_STAIRS.get())
                .add(ModBlocks.YELLOW_WOOD_SLAB.get())
                .add(ModBlocks.YELLOW_WOOD_BUTTON.get())
                .add(ModBlocks.YELLOW_WOOD_PRESSURE_PLATE.get())
                .add(ModBlocks.YELLOW_WOOD_FENCE.get())
                .add(ModBlocks.YELLOW_WOOD_FENCE_GATE.get())
                .add(ModBlocks.YELLOW_WOOD_DOOR.get())
                .add(ModBlocks.YELLOW_WOOD_TRAPDOOR.get())
                
                .add(ModBlocks.PURPLE_LOG.get())
                .add(ModBlocks.PURPLE_WOOD.get())
                .add(ModBlocks.STRIPPED_PURPLE_WOOD.get())
                .add(ModBlocks.STRIPPED_PURPLE_LOG.get())
                .add(ModBlocks.PURPLE_PLANK.get())
                .add(ModBlocks.PURPLE_WOOD_STAIRS.get())
                .add(ModBlocks.PURPLE_WOOD_SLAB.get())
                .add(ModBlocks.PURPLE_WOOD_BUTTON.get())
                .add(ModBlocks.PURPLE_WOOD_PRESSURE_PLATE.get())
                .add(ModBlocks.PURPLE_WOOD_FENCE.get())
                .add(ModBlocks.PURPLE_WOOD_FENCE_GATE.get())
                .add(ModBlocks.PURPLE_WOOD_DOOR.get())
                .add(ModBlocks.PURPLE_WOOD_TRAPDOOR.get())
                
                .add(ModBlocks.CYAN_LOG.get())
                .add(ModBlocks.CYAN_WOOD.get())
                .add(ModBlocks.STRIPPED_CYAN_WOOD.get())
                .add(ModBlocks.STRIPPED_CYAN_LOG.get())
                .add(ModBlocks.CYAN_PLANK.get())
                .add(ModBlocks.CYAN_WOOD_STAIRS.get())
                .add(ModBlocks.CYAN_WOOD_SLAB.get())
                .add(ModBlocks.CYAN_WOOD_BUTTON.get())
                .add(ModBlocks.CYAN_WOOD_PRESSURE_PLATE.get())
                .add(ModBlocks.CYAN_WOOD_FENCE.get())
                .add(ModBlocks.CYAN_WOOD_FENCE_GATE.get())
                .add(ModBlocks.CYAN_WOOD_DOOR.get())
                .add(ModBlocks.CYAN_WOOD_TRAPDOOR.get())
                
                .add(ModBlocks.ORANGE_LOG.get())
                .add(ModBlocks.ORANGE_WOOD.get())
                .add(ModBlocks.STRIPPED_ORANGE_WOOD.get())
                .add(ModBlocks.STRIPPED_ORANGE_LOG.get())
                .add(ModBlocks.ORANGE_PLANK.get())
                .add(ModBlocks.ORANGE_WOOD_STAIRS.get())
                .add(ModBlocks.ORANGE_WOOD_SLAB.get())
                .add(ModBlocks.ORANGE_WOOD_BUTTON.get())
                .add(ModBlocks.ORANGE_WOOD_PRESSURE_PLATE.get())
                .add(ModBlocks.ORANGE_WOOD_FENCE.get())
                .add(ModBlocks.ORANGE_WOOD_FENCE_GATE.get())
                .add(ModBlocks.ORANGE_WOOD_DOOR.get())
                .add(ModBlocks.ORANGE_WOOD_TRAPDOOR.get())
                
                .add(ModBlocks.LIME_LOG.get())
                .add(ModBlocks.LIME_WOOD.get())
                .add(ModBlocks.STRIPPED_LIME_WOOD.get())
                .add(ModBlocks.STRIPPED_LIME_LOG.get())
                .add(ModBlocks.LIME_PLANK.get())
                .add(ModBlocks.LIME_WOOD_STAIRS.get())
                .add(ModBlocks.LIME_WOOD_SLAB.get())
                .add(ModBlocks.LIME_WOOD_BUTTON.get())
                .add(ModBlocks.LIME_WOOD_PRESSURE_PLATE.get())
                .add(ModBlocks.LIME_WOOD_FENCE.get())
                .add(ModBlocks.LIME_WOOD_FENCE_GATE.get())
                .add(ModBlocks.LIME_WOOD_DOOR.get())
                .add(ModBlocks.LIME_WOOD_TRAPDOOR.get())
                
                .add(ModBlocks.PINK_LOG.get())
                .add(ModBlocks.PINK_WOOD.get())
                .add(ModBlocks.STRIPPED_PINK_WOOD.get())
                .add(ModBlocks.STRIPPED_PINK_LOG.get())
                .add(ModBlocks.PINK_PLANK.get())
                .add(ModBlocks.PINK_WOOD_STAIRS.get())
                .add(ModBlocks.PINK_WOOD_SLAB.get())
                .add(ModBlocks.PINK_WOOD_BUTTON.get())
                .add(ModBlocks.PINK_WOOD_PRESSURE_PLATE.get())
                .add(ModBlocks.PINK_WOOD_FENCE.get())
                .add(ModBlocks.PINK_WOOD_FENCE_GATE.get())
                .add(ModBlocks.PINK_WOOD_DOOR.get())
                .add(ModBlocks.PINK_WOOD_TRAPDOOR.get())
                
                .add(ModBlocks.BROWN_LOG.get())
                .add(ModBlocks.BROWN_WOOD.get())
                .add(ModBlocks.STRIPPED_BROWN_WOOD.get())
                .add(ModBlocks.STRIPPED_BROWN_LOG.get())
                .add(ModBlocks.BROWN_PLANK.get())
                .add(ModBlocks.BROWN_WOOD_STAIRS.get())
                .add(ModBlocks.BROWN_WOOD_SLAB.get())
                .add(ModBlocks.BROWN_WOOD_BUTTON.get())
                .add(ModBlocks.BROWN_WOOD_PRESSURE_PLATE.get())
                .add(ModBlocks.BROWN_WOOD_FENCE.get())
                .add(ModBlocks.BROWN_WOOD_FENCE_GATE.get())
                .add(ModBlocks.BROWN_WOOD_DOOR.get())
                .add(ModBlocks.BROWN_WOOD_TRAPDOOR.get())
                
                .add(ModBlocks.BLACK_LOG.get())
                .add(ModBlocks.BLACK_WOOD.get())
                .add(ModBlocks.STRIPPED_BLACK_WOOD.get())
                .add(ModBlocks.STRIPPED_BLACK_LOG.get())
                .add(ModBlocks.BLACK_PLANK.get())
                .add(ModBlocks.BLACK_WOOD_STAIRS.get())
                .add(ModBlocks.BLACK_WOOD_SLAB.get())
                .add(ModBlocks.BLACK_WOOD_BUTTON.get())
                .add(ModBlocks.BLACK_WOOD_PRESSURE_PLATE.get())
                .add(ModBlocks.BLACK_WOOD_FENCE.get())
                .add(ModBlocks.BLACK_WOOD_FENCE_GATE.get())
                .add(ModBlocks.BLACK_WOOD_DOOR.get())
                .add(ModBlocks.BLACK_WOOD_TRAPDOOR.get())
                
                .add(ModBlocks.WHITE_LOG.get())
                .add(ModBlocks.WHITE_WOOD.get())
                .add(ModBlocks.STRIPPED_WHITE_WOOD.get())
                .add(ModBlocks.STRIPPED_WHITE_LOG.get())
                .add(ModBlocks.WHITE_PLANK.get())
                .add(ModBlocks.WHITE_WOOD_STAIRS.get())
                .add(ModBlocks.WHITE_WOOD_SLAB.get())
                .add(ModBlocks.WHITE_WOOD_BUTTON.get())
                .add(ModBlocks.WHITE_WOOD_PRESSURE_PLATE.get())
                .add(ModBlocks.WHITE_WOOD_FENCE.get())
                .add(ModBlocks.WHITE_WOOD_FENCE_GATE.get())
                .add(ModBlocks.WHITE_WOOD_DOOR.get())
                .add(ModBlocks.WHITE_WOOD_TRAPDOOR.get())
                
                .add(ModBlocks.GRAY_LOG.get())
                .add(ModBlocks.GRAY_WOOD.get())
                .add(ModBlocks.STRIPPED_GRAY_WOOD.get())
                .add(ModBlocks.STRIPPED_GRAY_LOG.get())
                .add(ModBlocks.GRAY_PLANK.get())
                .add(ModBlocks.GRAY_WOOD_STAIRS.get())
                .add(ModBlocks.GRAY_WOOD_SLAB.get())
                .add(ModBlocks.GRAY_WOOD_BUTTON.get())
                .add(ModBlocks.GRAY_WOOD_PRESSURE_PLATE.get())
                .add(ModBlocks.GRAY_WOOD_FENCE.get())
                .add(ModBlocks.GRAY_WOOD_FENCE_GATE.get())
                .add(ModBlocks.GRAY_WOOD_DOOR.get())
                .add(ModBlocks.GRAY_WOOD_TRAPDOOR.get())
                
                .add(ModBlocks.LIGHT_GRAY_LOG.get())
                .add(ModBlocks.LIGHT_GRAY_WOOD.get())
                .add(ModBlocks.STRIPPED_LIGHT_GRAY_WOOD.get())
                .add(ModBlocks.STRIPPED_LIGHT_GRAY_LOG.get())
                .add(ModBlocks.LIGHT_GRAY_PLANK.get())
                .add(ModBlocks.LIGHT_GRAY_WOOD_STAIRS.get())
                .add(ModBlocks.LIGHT_GRAY_WOOD_SLAB.get())
                .add(ModBlocks.LIGHT_GRAY_WOOD_BUTTON.get())
                .add(ModBlocks.LIGHT_GRAY_WOOD_PRESSURE_PLATE.get())
                .add(ModBlocks.LIGHT_GRAY_WOOD_FENCE.get())
                .add(ModBlocks.LIGHT_GRAY_WOOD_FENCE_GATE.get())
                .add(ModBlocks.LIGHT_GRAY_WOOD_DOOR.get())
                .add(ModBlocks.LIGHT_GRAY_WOOD_TRAPDOOR.get())
                
                .add(ModBlocks.LIGHT_BLUE_LOG.get())
                .add(ModBlocks.LIGHT_BLUE_WOOD.get())
                .add(ModBlocks.STRIPPED_LIGHT_BLUE_WOOD.get())
                .add(ModBlocks.STRIPPED_LIGHT_BLUE_LOG.get())
                .add(ModBlocks.LIGHT_BLUE_PLANK.get())
                .add(ModBlocks.LIGHT_BLUE_WOOD_STAIRS.get())
                .add(ModBlocks.LIGHT_BLUE_WOOD_SLAB.get())
                .add(ModBlocks.LIGHT_BLUE_WOOD_BUTTON.get())
                .add(ModBlocks.LIGHT_BLUE_WOOD_PRESSURE_PLATE.get())
                .add(ModBlocks.LIGHT_BLUE_WOOD_FENCE.get())
                .add(ModBlocks.LIGHT_BLUE_WOOD_FENCE_GATE.get())
                .add(ModBlocks.LIGHT_BLUE_WOOD_DOOR.get())
                .add(ModBlocks.LIGHT_BLUE_WOOD_TRAPDOOR.get())
                
                .add(ModBlocks.MAGENTA_LOG.get())
                .add(ModBlocks.MAGENTA_WOOD.get())
                .add(ModBlocks.STRIPPED_MAGENTA_WOOD.get())
                .add(ModBlocks.STRIPPED_MAGENTA_LOG.get())
                .add(ModBlocks.MAGENTA_PLANK.get())
                .add(ModBlocks.MAGENTA_WOOD_STAIRS.get())
                .add(ModBlocks.MAGENTA_WOOD_SLAB.get())
                .add(ModBlocks.MAGENTA_WOOD_BUTTON.get())
                .add(ModBlocks.MAGENTA_WOOD_PRESSURE_PLATE.get())
                .add(ModBlocks.MAGENTA_WOOD_FENCE.get())
                .add(ModBlocks.MAGENTA_WOOD_FENCE_GATE.get())
                .add(ModBlocks.MAGENTA_WOOD_DOOR.get())
                .add(ModBlocks.MAGENTA_WOOD_TRAPDOOR.get())

                ;

        tag(BlockTags.FENCES)
                .add(ModBlocks.RED_WOOD_FENCE.get())
                .add(ModBlocks.BLUE_WOOD_FENCE.get())
                .add(ModBlocks.GREEN_WOOD_FENCE.get())
                .add(ModBlocks.YELLOW_WOOD_FENCE.get())
                .add(ModBlocks.PURPLE_WOOD_FENCE.get())
                .add(ModBlocks.CYAN_WOOD_FENCE.get())
                .add(ModBlocks.ORANGE_WOOD_FENCE.get())
                .add(ModBlocks.LIME_WOOD_FENCE.get())
                .add(ModBlocks.PINK_WOOD_FENCE.get())
                .add(ModBlocks.BROWN_WOOD_FENCE.get())
                .add(ModBlocks.BLACK_WOOD_FENCE.get())
                .add(ModBlocks.WHITE_WOOD_FENCE.get())
                .add(ModBlocks.GRAY_WOOD_FENCE.get())
                .add(ModBlocks.LIGHT_GRAY_WOOD_FENCE.get())
                .add(ModBlocks.LIGHT_BLUE_WOOD_FENCE.get())
                .add(ModBlocks.MAGENTA_WOOD_FENCE.get())

                ;

        tag(BlockTags.FENCE_GATES)

                .add(ModBlocks.RED_WOOD_FENCE_GATE.get())
                .add(ModBlocks.BLUE_WOOD_FENCE_GATE.get())
                .add(ModBlocks.GREEN_WOOD_FENCE_GATE.get())
                .add(ModBlocks.YELLOW_WOOD_FENCE_GATE.get())
                .add(ModBlocks.PURPLE_WOOD_FENCE_GATE.get())
                .add(ModBlocks.CYAN_WOOD_FENCE_GATE.get())
                .add(ModBlocks.ORANGE_WOOD_FENCE_GATE.get())
                .add(ModBlocks.LIME_WOOD_FENCE_GATE.get())
                .add(ModBlocks.PINK_WOOD_FENCE_GATE.get())
                .add(ModBlocks.BROWN_WOOD_FENCE_GATE.get())
                .add(ModBlocks.BLACK_WOOD_FENCE_GATE.get())
                .add(ModBlocks.WHITE_WOOD_FENCE_GATE.get())
                .add(ModBlocks.GRAY_WOOD_FENCE_GATE.get())
                .add(ModBlocks.LIGHT_GRAY_WOOD_FENCE_GATE.get())
                .add(ModBlocks.LIGHT_BLUE_WOOD_FENCE_GATE.get())
                .add(ModBlocks.MAGENTA_WOOD_FENCE_GATE.get())

                ;
    }
}
